// <auto-generated> This file has been auto generated. </auto-generated>
using System;

namespace Microsoft.VisualStudio
{
    internal class TestPlatform
    {
        internal class TestSDKAutoGeneratedCodeAttribute : Attribute
        {
        }
    }
}